#!/bin/bash
# Quick Start Guide - DataLukas

echo "═══════════════════════════════════════"
echo "  DataLukas - Quick Start"
echo "═══════════════════════════════════════"
echo ""

echo "1️⃣  Instalar dependências:"
echo "   NODE_ENV=development npm install"
echo ""

echo "2️⃣  Rodar em desenvolvimento:"
echo "   npm run dev"
echo "   → Acesse: http://localhost:5173"
echo ""

echo "3️⃣  Build para produção:"
echo "   npm run build"
echo "   → Output: dist/"
echo ""

echo "4️⃣  Preview da build:"
echo "   npm run preview"
echo ""

echo "═══════════════════════════════════════"
echo "  Credenciais de Acesso"
echo "═══════════════════════════════════════"
echo ""
echo "Admin:"
echo "  Login: admin"
echo "  Senha: admin"
echo ""
echo "Funcionários:"
echo "  Login: andrade | Senha: andrade"
echo "  Login: leo     | Senha: leo"
echo "  Login: rallyson| Senha: rallyson"
echo "  Login: william | Senha: william"
echo "  Login: helder  | Senha: helder"
echo ""

echo "═══════════════════════════════════════"
echo "  Status do Projeto"
echo "═══════════════════════════════════════"
echo ""
echo "✅ Vite + React + TypeScript"
echo "✅ 8 componentes modulares"
echo "✅ CSS original preservado"
echo "✅ Estado em memória (LocalStorage ready)"
echo "✅ Firebase configurado (Etapa 2)"
echo "✅ Build otimizado (96KB gzipped)"
echo ""
echo "📄 Documentação:"
echo "   - README.md"
echo "   - ETAPA1_CONCLUIDA.md"
echo "   - ESTRUTURA_CRIADA.md"
echo ""
